In [139]:
from sklearn.manifold import TSNE
import pandas as pd
import numpy as np

In [140]:
pred = pd.read_csv('../Data/UserRec/Prediction/rating_hat_svd.csv')
pred.set_index('userId', inplace=True)
pred

,1,2,3,5,6,7,9,10,11,12,...,159093,164179,166528,168250,168252,174055,176371,177765,179819,187593
userId,,,,,,,,,,,,,,,,,,,,,
1,4.300452,3.571215,3.465611,3.121505,4.066646,3.270388,3.162101,3.537795,3.722770,2.611431,...,3.460379,4.074908,3.972873,3.623153,4.321035,3.530005,3.834063,3.473022,3.587518,3.836080
2,3.965650,3.426945,3.254993,3.027813,3.930104,3.179177,3.108605,3.469403,3.657179,2.566144,...,3.429482,4.024593,3.951776,3.608948,4.262222,3.418126,3.748675,3.415725,3.497591,3.801226
3,3.928969,3.426830,3.233969,3.015313,3.919441,3.150855,3.090178,3.505553,3.650476,2.559769,...,3.407699,3.996506,3.935214,3.587564,4.231940,3.388216,3.713173,3.396671,3.474757,3.774202
4,3.938105,3.299268,3.236504,3.020118,3.900940,3.191719,3.110811,3.431941,3.617828,2.554367,...,3.428248,4.026593,3.928653,3.605687,4.265009,3.400778,3.761094,3.390869,3.470251,3.808670
5,3.947456,3.394174,3.240750,3.021619,3.920893,3.178373,3.109313,3.468222,3.646452,2.562202,...,3.432139,4.026257,3.951045,3.612065,4.264319,3.415271,3.751588,3.412719,3.492526,3.805632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,3.977969,3.361626,3.238261,3.005878,3.888173,3.211201,3.118615,3.294475,3.615175,2.541222,...,3.454113,4.056467,3.955322,3.632875,4.297632,3.461753,3.804884,3.429794,3.517901,3.836895
607,4.077525,3.499990,3.362884,3.099039,4.013268,3.210239,3.129586,3.596113,3.722045,2.613128,...,3.423394,4.029076,3.950237,3.597357,4.265653,3.410876,3.744931,3.415197,3.503393,3.793356
608,3.177097,3.340925,2.628582,2.705825,3.634920,2.911648,3.016721,3.415705,3.515043,2.427568,...,3.488664,3.994867,4.101642,3.723660,4.230316,3.386771,3.646825,3.483265,3.488309,3.835197
609,3.924542,3.395910,3.226975,3.015160,3.908441,3.175091,3.105838,3.437494,3.644628,2.558816,...,3.431677,4.026036,3.951851,3.613383,4.263199,3.410861,3.748753,3.411667,3.489919,3.805184
610,4.246273,3.730595,3.358404,3.029709,4.032689,3.191098,3.131468,3.534508,3.701156,2.564545,...,3.477751,4.061532,4.030413,3.648586,4.311851,3.604384,3.821525,3.539594,3.653686,3.835253

In [141]:
movies_info = pd.read_csv('../Data/UserRec/IMDB_movie.csv')
movies_info

,primaryTitle,movieId,T_Const,startYear,averageRating,numVotes,Family,Biography,Musical,Reality-TV,...,Romance,History,Film-Noir,Adult,Animation,News,Horror,Western,Sci-Fi,Crime
0,Nosferatu,1,13442,-0.758471,0.128628,-0.053772,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,Metropolis,2,17136,-0.706388,0.187451,-0.024546,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,City Lights,3,21749,-0.664721,0.216863,-0.020628,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,Frankenstein,5,21884,-0.664721,0.113922,-0.063186,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,M,6,22100,-0.664721,0.187451,-0.030754,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2099,Guardians of the Galaxy Vol. 2,174055,3896198,0.231112,0.084510,0.162868,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2100,Avengers: Infinity War,176371,4154756,0.241529,0.202157,0.306884,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2101,Dunkirk,177765,5013056,0.231112,0.113922,0.154600,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2102,Get Out,179819,5052448,0.231112,0.099216,0.128842,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2103,Deadpool 2,187593,5463162,0.241529,0.099216,0.125068,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## T-SNE

In [142]:
movies_info

,primaryTitle,movieId,T_Const,startYear,averageRating,numVotes,Family,Biography,Musical,Reality-TV,...,Romance,History,Film-Noir,Adult,Animation,News,Horror,Western,Sci-Fi,Crime
0,Nosferatu,1,13442,-0.758471,0.128628,-0.053772,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,Metropolis,2,17136,-0.706388,0.187451,-0.024546,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,City Lights,3,21749,-0.664721,0.216863,-0.020628,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,Frankenstein,5,21884,-0.664721,0.113922,-0.063186,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,M,6,22100,-0.664721,0.187451,-0.030754,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2099,Guardians of the Galaxy Vol. 2,174055,3896198,0.231112,0.084510,0.162868,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2100,Avengers: Infinity War,176371,4154756,0.241529,0.202157,0.306884,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2101,Dunkirk,177765,5013056,0.231112,0.113922,0.154600,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2102,Get Out,179819,5052448,0.231112,0.099216,0.128842,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2103,Deadpool 2,187593,5463162,0.241529,0.099216,0.125068,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [143]:
df=movies_info.copy()
user_rating = pred.loc[600]
type(user_rating)

pandas.core.series.Series

In [144]:
movies_features = movies_info.drop(columns=['primaryTitle', 'T_Const', 'movieId'])

tsne_score = TSNE(n_components=1, learning_rate='auto', init='random').fit_transform(np.array(movies_features))

In [145]:
def tSNE(movie_df):
    movies_features = movie_df.drop(columns=['primaryTitle', 'T_Const', 'movieId'])

    tsne_score = TSNE(n_components=1, learning_rate='auto', init='random').fit_transform(np.array(movies_features))

    movies_sort = movie_df[['T_Const', 'primaryTitle', 'movieId']].copy()
    movies_sort['tsne_score'] = tsne_score
    
    movies_sort.sort_values(by=['tsne_score'], inplace=True)

    movies_sort.reset_index(drop=True, inplace=True)

    return movies_sort
    

movies_sorted = tSNE(movies_info)
movies_sorted

      T_Const                         primaryTitle  movieId  tsne_score
0      120735  Lock, Stock and Two Smoking Barrels     3409 -118.955666
1     1250777                             Kick-Ass    90866 -118.916534
2     1232829                       21 Jump Street    89904 -118.875488
3     3799694                        The Nice Guys   168252 -118.866417
4     2294449                       22 Jump Street   122900 -118.823410
...       ...                                  ...      ...         ...
2099  1748122                     Moonrise Kingdom   110553  110.142113
2100  1570728                 Crazy, Stupid, Love.   103335  110.155510
2101  1022603                   500 Days of Summer    79592  110.213120
2102  1045658              Silver Linings Playbook    80906  110.365158
2103   118799                    Life Is Beautiful     3005  110.525307

[2104 rows x 4 columns]

In [146]:
movies_sorted.shape

(2104, 4)

In [149]:
movies_sorted.to_csv('../Data/UserRec/recommend/tSNE_sorted.csv')

## Rec

In [147]:
def tSNE_recommend(title, sorted_movies_df, range=20, n=5):
    movie_index = sorted_movies_df.index[sorted_movies_df['primaryTitle'] == title].tolist()
    
    if movie_index:
        movie_index = movie_index[0]

        len = sorted_movies_df.shape[0]
        if range > len-2:
            return 'Range out of list'

        front = movie_index - range//2 
        back = movie_index + range//2 

        if front < 0:
            back += -front
            front = 0
        elif back > len-1:
            front -= back - (len-1)
            back = len-1
        
        similar_movie_df = sorted_movies_df[front:back].drop(index = movie_index)
        
        return similar_movie_df
    
    else:
        return 'Can\'t Find this Movie'


def user_recommend(user_id, similar_movie_df, n=5):
    sorted_id = list(pred.loc[user_id].sort_values(ascending=False).index)
    i = 0
    range_movie_id = similar_movie_df['movieId'].to_list()
    rec_id_list = []
    for index in range(len(sorted_id)):
        if i >=  n:
            break
        else:
            if int(sorted_id[index]) in range_movie_id:
                rec_id_list.append(similar_movie_df[similar_movie_df['movieId'] == int(sorted_id[index])].index.to_list()[0])
                i += 1
    
    ## get movie name
    id_name = similar_movie_df['primaryTitle'].to_dict()

    name_list = []
    for id in rec_id_list:
        name_list.append(id_name[id])

    return name_list

In [148]:
movie = 'The Avengers'
user_id = 50


similar_movie_df = tSNE_recommend(movie, movies_sorted)

user_recommend(user_id, similar_movie_df)

['Harry Potter and the Half-Blood Prince',
 'Edge of Tomorrow',
 'The Chronicles of Narnia: Prince Caspian',
 'X-Men: Days of Future Past',
 'Avengers: Infinity War']

In [176]:
id_name = movies_sorted.set_index('movieId')['primaryTitle'].to_dict()

In [178]:
id_name

{3409: 'Lock, Stock and Two Smoking Barrels',
 90866: 'Kick-Ass',
 89904: '21 Jump Street',
 168252: 'The Nice Guys',
 122900: '22 Jump Street',
 90746: 'RED',
 70183: 'Pineapple Express',
 106782: 'Kick-Ass 2',
 30816: 'The Blind Swordsman: Zatoichi',
 8985: 'Mr. & Mrs. Smith',
 96588: 'The Other Guys',
 3479: 'Rush Hour',
 3104: 'Grosse Pointe Blank',
 4254: 'Bad Boys II',
 2085: 'The Mask',
 6059: 'Rush Hour 2',
 2247: 'Bad Boys',
 1220: 'Midnight Run',
 4975: 'Miss Congeniality',
 76175: 'The Green Hornet',
 805: 'Beverly Hills Cop',
 2384: 'Rumble in the Bronx',
 1097: 'Beverly Hills Cop II',
 1342: 'Kindergarten Cop',
 902: 'Repo Man',
 599: '48 Hrs.',
 1298: 'Dick Tracy',
 2411: 'Money Train',
 1974: 'Beverly Hills Cop III',
 4890: "Big Momma's House",
 2991: 'Blues Brothers 2000',
 1441: 'The Silence of the Lambs',
 46723: 'The Departed',
 1619: 'Reservoir Dogs',
 58293: 'No Country for Old Men',
 136020: 'Nightcrawler',
 68554: 'The Town',
 37727: 'Crash',
 49649: 'Lucky Number Slevin',
 61323: 'Eastern Promises',
 4848: 'The Bank Job',
 7163: '21 Grams',
 5782: 'Road to Perdition',
 59784: 'Fracture',
 6620: 'Red Dragon',
 3147: 'Jackie Brown',
 4361: 'Traffic',
 5812: 'Panic Room',
 4980: 'Hannibal',
 3784: 'The Talented Mr. Ripley',
 7153: 'Runaway Jury',
 5618: 'John Q',
 6874: 'Dirty Pretty Things',
 5943: 'Frailty',
 2857: 'Sleepers',
 4874: 'Sexy Beast',
 3262: 'A Simple Plan',
 2915: 'A Time to Kill',
 4367: 'Boiler Room',
 3213: 'The Rainmaker',
 3033: 'Cop Land',
 1719: "Carlito's Way",
 3461: 'A Perfect Murder',
 1892: 'A Perfect World',
 1848: 'Menace II Society',
 1617: 'Red Rock West',
 2478: "Things to Do in Denver When You're Dead",
 1810: 'Kalifornia',
 1343: "Miller's Crossing",
 1321: 'The Grifters',
 1198: 'The Untouchables',
 810: 'Blood Simple',
 2724: 'The Juror',
 431: 'Marathon Man',
 112: 'On the Waterfront',
 56941: 'The Dark Knight',
 34520: 'Batman Begins',
 2081: 'Léon: The Professional',
 6016: 'Kill Bill: Vol. 1',
 2379: 'Heat',
 157296: 'Sicario',
 3861: 'Training Day',
 40629: '3:10 to Yuma',
 8361: 'Man on Fire',
 33660: 'Collateral',
 45501: 'A History of Violence',
 1769: 'The Fugitive',
 37729: 'Layer Cake',
 44972: 'Brick',
 1747: 'Falling Down',
 2004: 'The Crow',
 3441: 'The Negotiator',
 2100: 'Natural Born Killers',
 3793: 'Arlington Road',
 3452: 'Payback',
 3070: 'Fallen',
 5065: 'The Score',
 1799: 'In the Line of Fire',
 1258: 'The Killer',
 2000: 'Clear and Present Danger',
 2761: 'The Long Kiss Goodnight',
 8373: 'The Punisher',
 2950: 'Absolute Power',
 3146: 'The Jackal',
 2739: 'Last Man Standing',
 2428: 'The Prophecy',
 2396: 'Just Cause',
 3039: "The Devil's Own",
 3438: 'Mercury Rising',
 2881: 'The Substitute',
 2416: 'The Net',
 595: 'The Professional',
 357: 'Enter the Dragon',
 355: 'Badlands',
 337: 'The French Connection',
 249: 'Bonnie and Clyde',
 103249: 'Captain Phillips',
 2402: 'Ghost in the Shell',
 6331: 'Cowboy Bebop: The Movie',
 2700: 'From Dusk Till Dawn',
 4344: 'Minority Report',
 6595: 'Daredevil',
 3798: 'Entrapment',
 1480: 'Batman Returns',
 2640: 'The Crow: City of Angels',
 12: 'The 39 Steps',
 6: 'M',
 419: 'Three Days of the Condor',
 107406: 'Now You See Me',
 1834: 'Malice',
 3489: 'Snake Eyes',
 59369: 'The Number 23',
 111: 'Dial M for Murder',
 2687: 'Fargo',
 2599: 'Bound',
 1380: 'Cape Fear',
 45720: 'Sin City',
 5283: "Ocean's Eleven",
 2136: 'Shallow Grave',
 4378: 'Phone Booth',
 60072: "Ocean's Thirteen",
 8961: "Ocean's Twelve",
 4007: 'The Thomas Crown Affair',
 2125: 'The River Wild',
 2474: 'Sudden Death',
 4027: 'Shaft',
 3219: 'The Replacement Killers',
 4128: 'Romeo Must Die',
 2664: 'Eraser',
 2243: 'Assassins',
 6548: 'Once Upon a Time in Mexico',
 44195: 'Transporter 2',
 3507: 'U.S. Marshals',
 5400: 'Swordfish',
 3615: 'Lethal Weapon 4',
 4621: 'Gone in 60 Seconds',
 2805: 'Ransom',
 73321: 'Machete',
 1591: 'El Mariachi',
 1589: 'Lethal Weapon 3',
 6754: 'The Transporter',
 6155: 'Spy Game',
 33615: 'Ong-Bak: The Thai Warrior',
 3016: 'Con Air',
 59022: 'Crank',
 2334: 'Desperado',
 60069: 'Wanted',
 3617: 'Ronin',
 7318: 'The Italian Job',
 1429: 'Point Break',
 1271: 'Lethal Weapon 2',
 80219: 'RocknRolla',
 3730: 'Run Lola Run',
 1136: 'Lethal Weapon',
 137857: 'John Wick',
 71264: 'Taken',
 332: 'Dirty Harry',
 39183: 'Kill Bill: Vol. 2',
 115569: 'Guardians of the Galaxy',
 98809: 'Deadpool',
 164179: 'Thor: Ragnarok',
 174055: 'Guardians of the Galaxy Vol. 2',
 135887: 'Kingsman: The Secret Service',
 187593: 'Deadpool 2',
 58803: 'Ant-Man',
 106072: 'The Man from U.N.C.L.E.',
 97913: 'Men in Black 3',
 135569: 'The Interview',
 143355: 'Now You See Me 2',
 3173: 'Men in Black',
 30810: 'The Life Aquatic with Steve Zissou',
 49286: 'Get Smart',
 533: 'The Blues Brothers',
 3257: 'Three Kings',
 1090: 'Star Trek IV: The Voyage Home',
 1028: 'Big Trouble in Little China',
 2087: 'Maverick',
 3435: 'The Mask of Zorro',
 2795: 'Muppet Treasure Island',
 8360: 'The Rundown',
 3972: 'Austin Powers: The Spy Who Shagged Me',
 904: 'Romancing the Stone',
 4447: 'Shanghai Noon',
 1131: 'Innerspace',
 1370: 'Teenage Mutant Ninja Turtles',
 2722: 'First Strike',
 5577: 'Rat Race',
 1021: 'Crocodile Dundee',
 3555: 'Men in Black II',
 1831: 'Last Action Hero',
 6755: 'Austin Powers in Goldmember',
 6296: 'Johnny English',
 6873: 'Shanghai Knights',
 1956: 'The Three Musketeers',
 3618: 'Small Soldiers',
 8981: 'The Brothers Grimm',
 934: 'The Jewel of the Nile',
 1457: 'Teenage Mutant Ninja Turtles II: The Secret of the Ooze',
 3483: 'Six Days Seven Nights',
 1037: 'The Golden Child',
 4019: "Charlie's Angels",
 2321: 'Cutthroat Island',
 5066: 'Spy Kids',
 1094: 'Crocodile Dundee II',
 3098: 'George of the Jungle',
 5265: 'Cats & Dogs',
 2802: 'The Phantom',
 6944: "Charlie's Angels: Full Throttle",
 786: 'Superman III',
 5128: 'Crocodile Dundee in Los Angeles',
 1955: 'Teenage Mutant Ninja Turtles III',
 1057: 'Howard the Duck',
 3893: 'Inspector Gadget',
 48394: 'Snakes on a Plane',
 3255: 'Speed 2: Cruise Control',
 4446: 'Reindeer Games',
 56367: 'The Fast and the Furious: Tokyo Drift',
 7373: '2 Fast 2 Furious',
 5785: 'S.W.A.T.',
 2135: 'The Shadow',
 5151: 'The Fast and the Furious',
 410: 'Jaws',
 231: 'Goldfinger',
 222: 'From Russia with Love',
 246: 'Thunderball',
 265: 'You Only Live Twice',
 296: "On Her Majesty's Secret Service",
 329: 'Diamonds Are Forever',
 362: 'Live and Let Die',
 379: 'The Man with the Golden Gun',
 468: 'The Spy Who Loved Me',
 653: 'First Blood',
 587: 'For Your Eyes Only',
 986: 'Rambo: First Blood Part II',
 1013: 'A View to a Kill',
 1171: 'The Living Daylights',
 1228: 'Rambo III',
 1272: 'Licence to Kill',
 1333: 'The Hunt for Red October',
 2010: 'Drop Zone',
 1721: 'Cliffhanger',
 2505: 'Under Siege 2: Dark Territory',
 2686: 'Executive Decision',
 2600: 'Broken Arrow',
 3034: "Dante's Peak",
 2942: 'Twister',
 3264: 'Tomorrow Never Dies',
 2371: 'GoldenEye',
 2141: 'Speed',
 4571: 'Space Cowboys',
 3916: 'The World Is Not Enough',
 6773: 'xXx',
 2808: 'The Rock',
 2336: 'Die Hard with a Vengeance',
 5464: 'Die Another Day',
 2791: 'Mission: Impossible',
 3439: 'Mission: Impossible II',
 7324: 'Mission: Impossible III',
 51077: 'The A-Team',
 94677: 'The Expendables',
 67255: 'Quantum of Solace',
 88125: 'The Bourne Legacy',
 122916: 'Spectre',
 122920: 'Mission: Impossible - Rogue Nation',
 40278: 'Casino Royale',
 81932: 'Skyfall',
 106489: 'How to Train Your Dragon 2',
 118696: 'Big Hero 6',
 69844: 'How to Train Your Dragon',
 98961: 'Rise of the Guardians',
 73017: 'The Adventures of Tintin',
 102445: 'The Lego Movie',
 53000: 'Kung Fu Panda',
 93363: 'Kung Fu Panda 2',
 57640: '9',
 7317: 'The Incredibles',
 3699: 'The Iron Giant',
 87520: 'Rango',
 1693: 'Batman: Mask of the Phantasm',
 1884: 'Ninja Scroll',
 4291: 'Final Fantasy: The Spirits Within',
 3556: 'Titan A.E.',
 5103: 'Atlantis: The Lost Empire',
 172: 'The Magnificent Seven',
 303: 'The Wild Bunch',
 2186: 'Wyatt Earp',
 7293: 'Hidalgo',
 3244: 'The Saint',
 4388: "A Knight's Tale",
 253: 'The Dirty Dozen',
 1250: 'Batman',
 839: 'Indiana Jones and the Temple of Doom',
 3360: 'The 13th Warrior',
 2249: 'Batman Forever',
 596: 'Indiana Jones and the Raiders of the Lost Ark',
 1269: 'Indiana Jones and the Last Crusade',
 33004: 'Indiana Jones and the Kingdom of the Crystal Skull',
 2143: 'Star Trek: Generations',
 163: 'North by Northwest',
 33493: 'National Treasure',
 56587: 'National Treasure: Book of Secrets',
 8917: 'Sky Captain and the World of Tomorrow',
 2312: 'Congo',
 103141: 'Sherlock Holmes: A Game of Shadows',
 76077: 'Sherlock Holmes',
 111759: 'Divergent',
 44555: '30 Days of Night',
 56174: '28 Weeks Later',
 1179: 'Predator',
 34048: 'Alien vs. Predator',
 2959: 'Anaconda',
 65230: 'World War Z',
 60684: 'The Chronicles of Narnia: Prince Caspian',
 1438: 'The Rocketeer',
 3421: 'Lost in Space',
 2409: 'Mighty Morphin Power Rangers: The Movie',
 53996: 'Eragon',
 48516: 'Harry Potter and the Half-Blood Prince',
 36519: 'Harry Potter and the Order of the Phoenix',
 1061: 'The Karate Kid Part II',
 95510: 'Inception',
 68954: 'The Avengers',
 176371: 'Avengers: Infinity War',
 96821: 'Mad Max: Fury Road',
 34162: 'Iron Man',
 122924: 'Star Wars: Episode VII - The Force Awakens',
 111781: 'Captain America: The Winter Soldier',
 159093: 'Captain America: Civil War',
 112290: 'X-Men: Days of Future Past',
 104913: 'Edge of Tomorrow',
 168250: 'Rogue One: A Star Wars Story',
 122922: 'Avengers: Age of Ultron',
 91500: 'X-Men: First Class',
 96737: 'The Hunger Games',
 63876: 'Star Trek',
 111743: 'Black Panther',
 112623: 'The Hunger Games: Catching Fire',
 119141: 'Spider-Man: Homecoming',
 97752: 'Star Trek Into Darkness',
 93326: 'Iron Man 3',
 62374: 'Man of Steel',
 1805: 'Jurassic Park',
 55290: 'Captain America: The First Avenger',
 3968: 'Spider-Man',
 89492: 'Iron Man 2',
 7173: 'Spider-Man 2',
 1022: 'Aliens',
 33794: 'Jurassic World',
 72011: 'The Amazing Spider-Man',
 48738: 'Transformers',
 3536: 'X-Men',
 39446: 'Serenity',
 3072: 'The Fifth Element',
 102407: 'Oblivion',
 139385: 'Batman v Superman: Dawn of Justice',
 107348: 'Pacific Rim',
 2713: 'Independence Day',
 152081: 'X-Men: Apocalypse',
 112183: 'The Amazing Spider-Man 2',
 135143: 'Star Trek Beyond',
 112852: 'The Hunger Games: Mockingjay - Part 1',
 64614: 'The Incredible Hulk',
 84374: 'TRON: Legacy',
 67734: 'Godzilla',
 37741: 'X-Men: The Last Stand',
 110102: "Ender's Game",
 45672: 'John Carter',
 47629: 'Spider-Man 3',
 52973: 'Terminator Salvation',
 97304: 'Transformers: Dark of the Moon',
 46578: 'War of the Worlds',
 7360: 'The Day After Tomorrow',
 81591: 'Transformers: Revenge of the Fallen',
 59900: 'Jumper',
 87306: '2012',
 8950: 'Superman Returns',
 3274: 'Armageddon',
 6787: 'The Chronicles of Riddick',
 3160: 'The Lost World: Jurassic Park',
 4034: 'Jurassic Park III',
 45728: 'Æon Flux',
 3752: 'Planet of the Apes',
 6242: 'The Time Machine',
 5673: 'Star Trek: Nemesis',
 3996: 'Deep Blue Sea',
 2671: 'Escape from L.A.',
 2973: 'The Avengers',
 4487: 'Battlefield Earth',
 3499: 'Star Trek: Insurrection',
 2532: 'Waterworld',
 1196: 'Superman IV: The Quest for Peace',
 3258: 'Starship Troopers',
 2144: 'Stargate',
 1371: 'Total Recall',
 1449: 'Star Trek VI: The Undiscovered Country',
 953: 'Mad Max Beyond Thunderdome',
 832: 'Dune',
 909: 'Star Trek III: The Search for Spock',
 733: 'TRON',
 516: 'Moonraker',
 551: 'Superman II',
 585: 'Escape from New York',
 514: 'Mad Max',
 593: 'The Road Warrior',
 714: 'Star Trek II: The Wrath of Khan',
 428: "Logan's Run",
 307: 'Beneath the Planet of the Apes',
 491: 'Superman',
 640: 'E.T. the Extra-Terrestrial',
 150: 'Forbidden Planet',
 266: '2001: A Space Odyssey',
 276: 'Planet of the Apes',
 849: 'Nausicaä of the Valley of the Wind',
 10: 'King Kong',
 527: 'Star Trek: The Motion Picture',
 800: '2010: The Year We Make Contact',
 99007: 'Prometheus',
 4370: 'Mission to Mars',
 370: 'Soylent Green',
 327: 'A Clockwork Orange',
 1188: 'RoboCop',
 3062: 'Face/Off',
 1358: 'RoboCop 2',
 54997: 'Deja Vu',
 94959: 'Dredd',
 2145: 'Timecop',
 1911: 'RoboCop 3',
 2394: 'Judge Dredd',
 2529: 'Virtuosity',
 111360: 'The Maze Runner',
 106696: 'Super 8',
 8914: 'I, Robot',
 3256: 'Sphere',
 8798: 'Paycheck',
 5010: 'The 6th Day',
 2476: 'Tank Girl',
 88744: "The World's End",
 3534: 'Wild Wild West',
 2571: 'Barb Wire',
 2985: 'Batman & Robin',
 33836: 'Ultraviolet',
 6586: 'Hulk',
 1674: 'Universal Soldier',
 1203: 'Alien Nation',
 342: 'Conquest of the Planet of the Apes',
 333: 'Escape from the Planet of the Apes',
 4351: 'Terminator 3: Rise of the Machines',
 55765: 'X-Men Origins: Wolverine',
 98243: 'The Wolverine',
 5313: 'The Matrix Revolutions',
 5152: 'The Matrix Reloaded',
 911: 'The Terminator',
 1459: 'Terminator 2: Judgment Day',
 3751: 'The Matrix',
 3269: 'Volcano',
 2393: 'Johnny Mnemonic',
 2606: 'Chain Reaction',
 103228: 'Elysium',
 59315: 'I Am Legend',
 5225: 'Equilibrium',
 3355: 'Deep Impact',
 91529: 'Looper',
 93840: 'Rise of the Planet of the Apes',
 799: 'WarGames',
 101864: 'Gravity',
 610: 'Blade Runner',
 51935: 'V for Vendetta',
 4886: 'Children of Men',
 152077: 'Logan',
 2470: 'Species',
 27773: 'Blade: Trinity',
 4041: 'Hollow Man',
 1350: 'Predator 2',
 1476: 'Alien³',
 2952: 'Alien: Resurrection',
 7346: 'Resident Evil: Apocalypse',
 3477: 'Resident Evil',
 81834: 'Cloverfield',
 4638: 'Blade II',
 3791: 'Pitch Black',
 3300: 'Blade',
 30822: 'Dawn of the Dead',
 1373: 'Young Guns II',
 1244: 'Young Guns',
 107: 'The War of the Worlds',
 3397: 'Godzilla',
 372: 'Westworld',
 4823: 'Red Planet',
 6156: 'The One',
 1193: 'The Running Man',
 52281: 'Next',
 136864: 'Lucy',
 74789: 'Surrogates',
 1735: 'Demolition Man',
 86190: 'District 9',
 105844: 'In Time',
 6708: 'X2: X-Men United',
 45517: 'The Island',
 109374: 'Snowpiercer',
 53972: 'Sunshine',
 89470: 'Limitless',
 96079: 'The Adjustment Bureau',
 5872: 'Ghost Rider',
 45722: 'Underworld: Evolution',
 7371: 'Underworld',
 56775: "Shoot 'Em Up",
 2150: 'True Lies',
 2431: 'The Quick and the Dead',
 71530: 'Salt',
 3189: 'The Peacemaker',
 6709: 'The Recruit',
 8783: 'Live Free or Die Hard',
 79702: 'Death Proof',
 89745: 'Mission: Impossible - Ghost Protocol',
 1212: 'Die Hard',
 3763: 'The Siege',
 3361: 'Enemy of the State',
 1347: 'Nikita',
 1672: 'Under Siege',
 1299: 'Die Hard 2',
 3948: 'The Boondock Saints',
 1615: 'Patriot Games',
 926: 'F/X',
 56152: 'Grindhouse',
 64957: 'Angels & Demons',
 3020: 'Conspiracy Theory',
 63131: 'Jack Reacher',
 34319: 'The Bourne Supremacy',
 5816: 'The Bourne Identity',
 52975: 'The Bourne Ultimatum',
 61024: 'Body of Lies',
 4069: 'The Sum of All Fears',
 5072: 'Proof of Life',
 4016: 'Behind Enemy Lines',
 2951: 'Air Force One',
 66097: 'Shooter',
 2423: 'Outbreak',
 2318: 'Crimson Tide',
 2140: 'The Specialist',
 900: 'Red Dawn',
 194: 'Yojimbo',
 4963: 'The Cell',
 493: 'Alien',
 1587: 'The Lawnmower Man',
 3175: 'Mimic',
 520: 'Phantasm',
 2716: 'The Island of Dr. Moreau',
 2528: 'Village of the Damned',
 69526: 'The Mist',
 2455: 'Screamers',
 3060: 'Event Horizon',
 1348: 'Pacific Heights',
 1291: 'Arachnophobia',
 1515: 'Candyman',
 1208: "Child's Play",
 1256: 'Dead Calm',
 830: 'Children of the Corn',
 1127: 'Hellraiser',
 4728: 'Final Destination',
 694: 'Poltergeist',
 474: 'Dawn of the Dead',
 480: 'Halloween',
 272: 'Night of the Living Dead',
 52245: 'The Descent',
 485: 'Jaws 2',
 2567: 'The Arrival',
 3868: 'The Thirteenth Floor',
 2502: '12 Monkeys',
 1245: "The 'Burbs",
 161: 'Vertigo',
 145: 'To Catch a Thief',
 3911: 'The Ninth Gate',
 2762: 'Lost Highway',
 7022: 'Identity',
 122: 'Rear Window',
 40732: 'The Da Vinci Code',
 52: 'The Third Man',
 84954: 'Shutter Island',
 4901: 'Memento',
 175: 'Psycho',
 5110: 'The Others',
 44022: 'Saw',
 538: 'Friday the 13th',
 4054: 'Stir of Echoes',
 3396: 'From Hell',
 91077: 'The Cabin in the Woods',
 179819: 'Get Out',
 427: 'King Kong',
 361: 'The Exorcist',
 382: 'The Texas Chain Saw Massacre',
 647: 'The Evil Dead',
 494: 'The Amityville Horror',
 880: 'A Nightmare on Elm Street',
 3969: 'Stigmata',
 54272: 'Hostel',
 719: 'The Thing',
 417: 'The Stepford Wives',
 3755: 'The Faculty',
 3551: 'eXistenZ',
 434: 'The Omen',
 421: 'Carrie',
 2822: 'Scream',
 4545: 'The Blair Witch Project',
 3246: 'Scream 2',
 6796: 'The Ring',
 51540: 'Saw II',
 4327: 'Ringu',
 41285: 'Silent Hill',
 3108: 'I Know What You Did Last Summer',
 3783: 'Scream 3',
 3703: 'I Still Know What You Did Last Summer',
 60040: 'Saw III',
 4238: 'The Haunting',
 54286: '1408',
 4029: 'Sleepy Hollow',
 2161: 'New Nightmare',
 2642: 'Diabolique',
 5956: 'The Mothman Prophecies',
 4022: 'What Lies Beneath',
 87222: '10 Cloverfield Lane',
 1665: 'Twin Peaks: Fire Walk with Me',
 1339: "Jacob's Ladder",
 3624: 'Cube',
 3826: 'Pi',
 215: 'The Birds',
 1175: 'A Nightmare on Elm Street 3: Dream Warriors',
 930: 'Fright Night',
 5444: 'Thir13en Ghosts',
 2912: 'Thinner',
 1: 'Nosferatu',
 4489: 'House on Haunted Hill',
 3980: 'End of Days',
 27808: 'Constantine',
 4223: 'The Sixth Sense',
 119145: 'Gone Girl',
 374: 'Chinatown',
 376: 'The Conversation',
 1479: 'Basic Instinct',
 261: 'In the Heat of the Night',
 33166: 'The Village',
 2313: 'Copycat',
 31410: 'Secret Window',
 45880: 'The Lives of Others',
 46972: 'Flightplan',
 3088: 'The Game',
 3253: 'The Spanish Prisoner',
 1753: 'The Firm',
 4149: 'Mulholland Drive',
 6385: 'Insomnia',
 3037: "The Devil's Advocate",
 3362: 'Eyes Wide Shut',
 3821: "The Astronaut's Wife",
 57368: 'Ex Machina',
 6659: 'The Butterfly Effect',
 44761: 'Primer',
 3089: 'Gattaca',
 95: 'High Noon',
 204: 'The Manchurian Candidate',
 196: 'Cape Fear',
 1950: 'Sliver',
 2006: 'Disclosure',
 1635: 'Single White Female',
 1104: 'Fatal Attraction',
 4084: 'Along Came a Spider',
 5957: 'One Hour Photo',
 2414: 'Murder in the First',
 1556: 'A Few Good Men',
 1344: 'Misery',
 31685: 'Syriana',
 49274: 'Hard Candy',
 104841: 'Contagion',
 5541: 'The Experiment',
 5449: 'Amores perros',
 30707: 'The Machinist',
 71745: 'Black Swan',
 69757: 'The Hurt Locker',
 2701: 'The Ghost and the Darkness',
 54259: 'Blood Diamond',
 344: 'Deliverance',
 224: 'Lord of the Flies',
 74458: 'Valkyrie',
 3978: 'Thirteen Days',
 111362: 'Zero Dark Thirty',
 1409: 'JFK',
 420: "All the President's Men",
 2788: 'Michael Collins',
 3869: 'The Insider',
 79695: 'Argo',
 115713: 'The Imitation Game',
 4161: 'The Lord of the Rings: The Return of the King',
 3418: 'The Lord of the Rings: The Fellowship of the Ring',
 4214: 'The Lord of the Rings: The Two Towers',
 4270: 'Gladiator',
 106920: 'The Revenant',
 116823: 'Dawn of the Planet of the Apes',
 57669: 'Apocalypto',
 27815: 'King Kong',
 60397: 'Letters from Iwo Jima',
 4642: 'Crouching Tiger, Hidden Dragon',
 6870: 'Hero',
 7367: 'Kingdom of Heaven',
 80489: 'The Book of Eli',
 5463: 'The Count of Monte Cristo',
 7143: 'Master and Commander: The Far Side of the World',
 5991: 'Battle Royale',
 41569: 'House of Flying Daggers',
 76251: 'Hanna',
 48774: 'Flags of Our Fathers',
 2871: 'Star Trek: First Contact',
 1586: 'The Last of the Mohicans',
 5219: 'Brotherhood of the Wolf',
 8958: 'King Arthur',
 3053: 'The Edge',
 4326: 'The Perfect Storm',
 3424: 'The Man in the Iron Mask',
 1431: 'Robin Hood: Prince of Thieves',
 1242: 'Willow',
 3198: 'The Postman',
 4679: 'Vertical Limit',
 2355: 'First Knight',
 2641: 'Daylight',
 53322: '10,000 BC',
 350: 'The Poseidon Adventure',
 181: 'The Guns of Navarone',
 31: 'The Maltese Falcon',
 44: 'The Big Sleep',
 2459: 'Se7en',
 2527: 'The Usual Suspects',
 97225: 'Prisoners',
 158238: 'The Hateful Eight',
 3157: 'L.A. Confidential',
 103253: 'The Girl with the Dragon Tattoo',
 53464: 'Zodiac',
 7454: 'Mystic River',
 54999: 'Inside Man',
 85414: 'The Girl with the Dragon Tattoo',
 54995: 'Gone Baby Gone',
 2804: 'Primal Fear',
 56757: 'Michael Clayton',
 4558: 'Frequency',

In [175]:
id_name[3409]

'Lock, Stock and Two Smoking Barrels'

In [186]:
def user_general_rec(user_id, rating_pred, movie_df, n=5):
    sorted_id = list(rating_pred.loc[user_id].sort_values(ascending=False).index)
    id_name = movie_df.set_index('movieId')['primaryTitle'].to_dict()

    name_list = []
    for i in range(5):
        name_list.append(id_name[int(sorted_id[i])])

    return name_list

user_general_rec(20, pred, movies_sorted)

['Planes, Trains & Automobiles',
 'Hannah and Her Sisters',
 'Four Rooms',
 'Bananas',
 'The Full Monty']